### ISSUE TITLE
Prefer history.location over props.location

### ISSUE THREAD

**Issue by pbeshai** [pbeshai/react-url-query#22]
At least in latest react-router (v4.1.1), props.location can be out of sync with props.history.location during a change handler. Code should be updated to rely primarily on history.location if available.

**Comment by olizilla** [comment]
Just a heads, a similar issue is showing up for me with `react-router@2.8.1`.
I had `react-url-query` configured as per the readme:

```js
configureUrlQuery({history: browserHistory})
```
And found that the location object that `react-url-query` ended up using was occasionally out of sync which was difficult to debug, particularly when the `router.push` is used from other pages to jump to a specific `path` and `query`

From the changeset that fixed this issue, I figured it would be safe enough to pass in the `router` in place of the history for `react-router@2`, and making that change has fixed the issue.

Might be worth updating the README to warn people, or direct them to pass in the router rather than the history, to spare others this adventure. I should find the time to upgrade to react-router@4 but that's another story.

Thanks very much for your lib. It's cleared out a pile of bespoke query wrangling from my app with a nice, clean declarative recipe!
