### ISSUE TITLE
Updating url from an array

### ISSUE THREAD

**Issue by iwoork** [pbeshai/react-url-query#27]
Any example how to update the url when using an array? I tried using:

```
const urlPropsQueryConfig = {
  products: {
    type: UrlQueryParamTypes.array,
    queryParam: 'products'
  }
}
```
and it successfully gets the url values by manually passing parameters in the url 

```?products=value1_value2_value3```

when I tried to use:

```
onChangeProducts([value4])
```

it doesn't update the url and add the new product. onChangeProducts should update the url to:

```
?products=value1_value2_value3_value4
```

**Comment by pbeshai** [comment]
Ah, given your example I would expect the URL to update to `?products=value4` -- that isn't working?

**Comment by iwoork** [comment]
Yeah nothing happens. If it helps, I’m using React slingshot that uses react router 4.x. The onChange event doesn’t seem to trigger. I’m using checkboxes as well if that helps to understand.

**Comment by iwoork** [comment]
Ok I think I found the issue. On checkbox it needs to be:

```
onChange={()=> onChangeProducts([product.key, products])}
```

instead of just

```
onChange={onChangeProducts([product.key, products])}
```

Checkbox doesn't seem to remove the filter though if i click on it again (uncheck). It would be good if the onChange[XXX] should handle this out of the box?

**Comment by pbeshai** [comment]
Hi @iwoork, I think you may be misunderstanding how event handlers work in React. You should always be passing a function to them, which is why you can't pass `onChangeProducts(...)` -- this is the result of the function. 

You need to pass the entire updated array in there. It looks like you are not managing what is in your array properly. If `products` is an array of product keys, then when you add a new key, say key 5 to a list already containing 1,2,4, you are currently doing something like: [5, [1, 2, 4]], which is not the desired output.

To manage what is in the array you can do something more like:

```js
handleToggleProduct(productKey) {
  const { products, onChangeProducts } = this.props;

  let newProducts;

  // if we already have the product key in the array, remove it
  if (products.find(product => product.key === productKey)) {
    newProducts = products.filter(product => product.key !== productKey);
  
  // otherwise, we don't already have it so create a new array with it
  } else {
    newProducts = products.concat(productKey);
  }

  // pass the entire new array to the change handler
  onChangeProducts(newProducts);
}
```

Then you'd use it something like this:

```js
<input onChange={() => this.handleToggleProduct(product.key)} />
```

**Comment by pztrick** [comment]
@pbeshai I wrote a simple snippet to your example in your last comment, however, sending an empty array  `[]` does not unset the querystring value. It will add/remove elements just fine EXCEPT when you are removing the final element (e.g. passing `[]`). Then it keeps the element in the array.

```
class CheckboxFilter extends React.Component {
    handleClick(value) {
        var newFilters = this.props.parent.props.filter_era
        if(newFilters.find(item => item === value)){
            newFilters = newFilters.filter(item => item !== value)
        }else{
            newFilters.push(value)
        }
        
        // HERE: if newFilters is blank [] then it will not update.
        this.props.parent.props.onChangeFilter_era(newFilters)
    }

    render() {
         // ...snip...
    }
}

const urlPropsQueryConfig = {
    filter_era: { type: UrlQueryParamTypes.array, queryParam: 'era' },
}
```

If I set a bogus `static defaultProps = { filter_era: ['bogus value'] }` I can work around this behavior by just ignoring the bogus value in the 'business logic' of my app since it adds/removes the 2nd...Nth elements just fine, but would like advice on how to clear/reset the array (if not by just passing `[]` to the onChange function).

I can open a new issue but it is close code/use-case to earlier comment so figured it would provide context to post in this thread. :) Thanks!
