### ISSUE TITLE
Implementation Question

### ISSUE THREAD

**Issue by mhinc14** [pbeshai/react-url-query#56]
This is neither a feature or bug but an implementation question.

We need help with:

Understanding the best pattern/way to call an api that is dependant on props being made available from the url via 'react-url-query'

Currently: 

We are using react, redux and react-router v4.

We initialise a set of parameters in the url via the constructor().

```constructor(props) {
    super(props)
    this.state = {
    }

    multiPushInUrlQuery({
      selectedMetric: 'index',
      selectedSegment: 'age,
      xAxisQuestionId: 'q_1',
      yAxisQuestionId: 'q_2',
      xAxisAnswerId: 'a_1',
      yAxisAnswerId: 'a_1'
    })
    this.props.onChangeSelectedVariables(['age', 'gender'])
  }
```
We then inject the props we initialised into our component via addUrlProps().

This all works fine and the props are eventually available to us.

What we want is to understand how to call a a rest api that is dependant on these props. Eg. we need to pass 'xAxisQuestionId' as a parameter during our rest call.

currently we are trying to make the rest call during componentDidMount(). However the props we need to get from the url are undefined at the time componentDidMount is invoked.

```
componentDidMount() {

    const {selectedMetric, selectedSegment, xAxisQuestionId, yAxisQuestionId, xAxisAnswerId, yAxisAnswerId} = this.props

    this._fetchSomeDataViaRest(selectedMetric, selectedSegment, xAxisQuestionId, yAxisQuestionId, xAxisAnswerId, yAxisAnswerId)

  }
```

Ideally we need some pattern that helps us wait for the props we need to be defined before triggering the rest call.

**Comment by pbeshai** [comment]
So the problem is:

1. Nothing is set in the URL
2. Component gets mounted and URL is set, first render happens without URL params set
3. URL params set causing a re-render, now props available.

I guess I'd recommend using defaultProps for initial values when no props are set in the URL as opposed to pushing in the URL, then they'd be available immediately. Just set xAxisQuestionId default prop to q_1 as you would in any other react component. Also with this style you wouldn't need to update the URL on update since the params would be assumed to be default if not present.

Does that work for you?

**Comment by mhinc14** [comment]
Thanks for the reply. We went for your suggested approach. Thanks
