### ISSUE TITLE
PropTypes Deprication

### ISSUE THREAD

**Issue by carpiediem** [pbeshai/react-url-query#57]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Warning from ESLint: `React.PropTypes is deprecated since React 15.5.0, use the npm module prop-types instead`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
Compile demo code with babel

**What is the expected behavior?**
No deprecation warning

**Which versions of react-url-query, and which browser and OS are affected by this issue? Did this work in previous versions of react-url-query?**
current

**Comment by leonelgalan** [comment]
Everywhere in the code it says: `import PropTypes from 'prop-types';`, the only places where PropTypes was read from React was in:

* _docs/api/addUrlProps.md_:

```js
import React, { Component, PropTypes } from 'react';
```

* _README.md_:

```js
import React, { PureComponent, PropTypes } from 'react';
```

Because the issue mentions "demo code" it probably refers to the code in the documents. I can submit a PR, ~~are the docs coming from the docs folder in `master`?~~ My guess is `master`, the `gh-pages` branch? BTW, the `gh-pages` branch appears to be very old and outdated.

**Comment by carpiediem** [comment]
> Because the issue mentions "demo code" it probably refers to the code in the documents.

This is correct. Sorry for being unclear.
